Updated workflow

diff --git a/.github/workflows/deploy-curl-performance-test-branch.yaml b/.github/workflows/deploy-curl-performance-test-branch.yaml
--- a/.github/workflows/deploy-curl-performance-test-branch.yaml
+++ b/.github/workflows/deploy-curl-performance-test-branch.yaml
@@ -21,4 +21,105 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Run yamllint
-        run: yamllint -c ./.github/linters/.yaml-lint.yaml .github cloudformation
+        run: yamllint -c ./.github/linters/.yaml-lint.yaml .github/ cloudformation/
+
+  deploy-curl-performance-test:
+    environment:
+      name: production
+    name: Deploy curl performance test
+    needs: [lint]
+    runs-on: ubuntu-20.04
+    env:
+      account: K_AWS_01
+      python-version: [3.7]
+      region: ap-southeast-2
+
+    steps:
+      - uses: actions/checkout@v2
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ env.python-version }}
+
+      - name: aws-credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        env:
+          AWS_ACCESS_KEY_ID_NAME: ${{ env.account }}_ACCESS_KEY_ID
+          AWS_SECRET_ACCESS_KEY_NAME: ${{ env.account }}_SECRET_ACCESS_KEY
+          AWS_DEFAULT_REGION: ${{ env.region }}
+        with:
+          aws-access-key-id: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}
+          aws-secret-access-key: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}
+          aws-region: ${{ env.AWS_DEFAULT_REGION }}
+
+      - run: echo "accountid=$(aws sts get-caller-identity | jq -r .Account)" >> $GITHUB_ENV
+
+      - id: Bucket
+        env:
+          bucket-suffix: ${{ secrets.BUCKET_SUFFIX }}
+        run: |
+          echo "::set-output name=name::curl-performance-test-common-code-${{ env.accountid }}-${{ env.region }}-${{ env.bucket-suffix }}"
+
+      # Note: If deploying the Lambda Function in VPC
+      # - id: VpcInfo
+      #   run: |
+      #     if [[ "${{ env.accountid }}" == "123456789012" ]]
+      #     then
+      #       echo "::set-output name=vpcid::vpc-11111111"
+      #       echo "::set-output name=subnetid1::subnet-11111111"
+      #       echo "::set-output name=subnetid2::subnet-11111111"
+      #     else
+      #       echo "Error: ${{ env.accountid }} VPC info not found"
+      #       exit 1
+      #     fi
+
+      - name: Deploy curl-performance-test-common stack to ${{ env.accountid }}
+        uses: aws-actions/aws-cloudformation-github-deploy@v1
+        with:
+          capabilities: CAPABILITY_NAMED_IAM
+          name: curl-performance-test-common
+          no-fail-on-empty-changeset: 1
+          parameter-overrides: >-
+            BucketName=${{ steps.Bucket.outputs.name }},
+            NotificationURL=
+          template: ./cloudformation/curl-performance-test-common.yaml
+
+      - name: Upload URL lists to S3
+        run: |
+          aws s3 cp ./inputs/${{ env.accountid }}-${{ env.region }}.json s3://${{ steps.Bucket.outputs.name }}/inputs/ --region ${{ env.region }}
+
+      - name: Package and upload Lambda Function
+        id: LambdaPackage
+        run: |
+          zip -j curl-performance-test-$(git rev-parse --short HEAD).zip ./lambda/curl_performance_test.py
+          aws s3 cp curl-performance-test-$(git rev-parse --short HEAD).zip s3://${{ steps.Bucket.outputs.name }}/ --region ${{ env.region }}
+          echo "::set-output name=S3Key::curl-performance-test-$(git rev-parse --short HEAD).zip"
+
+      - name: Deploy curl-performance-test-main stack to ${{ env.accountid }}
+        uses: aws-actions/aws-cloudformation-github-deploy@v1
+        with:
+          name: curl-performance-test-main
+          capabilities: CAPABILITY_NAMED_IAM
+          no-fail-on-empty-changeset: 1
+          parameter-overrides: >-
+            ArtifactsBucketName=${{ steps.Bucket.outputs.name }},
+            CloudWatchCustomMetricNamespace=CurlPerformance,
+            LambdaFunctionName=curl-performance-test,
+            LambdaPackageS3Key=${{ steps.LambdaPackage.outputs.S3Key }},
+            ScheduleExpression=rate(0 minute),
+            SubnetId1=,
+            SubnetId2=,
+            VpcId=
+          # Note: Enable the following if running the lambda in VPC
+          # SubnetId1=${{ steps.VpcInfo.outputs.subnetid1 }},
+          # SubnetId2=${{ steps.VpcInfo.outputs.subnetid2 }},
+          # VpcId=${{ steps.VpcInfo.outputs.vpcid }}
+          template: ./cloudformation/curl-performance-test-main.yaml
+
+      - name: Deploy CloudWatch Dashboard
+        run: |
+          python3.7 -m venv env
+          source env/bin/activate
+          pip install -r scripts/requirements.txt
+          python3 scripts/deploy_dashboard.py -n CurlPerformance -f ./inputs/${{ env.accountid }}-${{ env.region }}.json -r ${{ env.region }}
+          deactivate
